import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const base = path.resolve(new URL('..', import.meta.url).pathname);
const userSearch = fs.readFileSync(path.join(base,'js/profile/user-search.js'),'utf8');
const rules = fs.readFileSync(path.join(base,'firebase/firestore.rules'),'utf8');
const fn = fs.readFileSync(path.join(base,'firebase/functions/index.js'),'utf8');
const helper = fs.readFileSync(path.join(base,'firebase/functions/publicProfileProjection.js'),'utf8');
assert.match(userSearch, /collection\(db, ["']publicProfiles["']\)/, 'visitor search must read publicProfiles');
assert.doesNotMatch(userSearch, /collection\(db, ["']users["']\)/, 'visitor search must not read users');
assert.match(rules, /match \/publicProfiles\/{uid}/);
assert.match(rules, /allow read: if true;/);
assert.match(rules, /allow write: if false; \/\/ Cloud Functions \/ Admin SDK only/);
assert.match(rules, /match \/users\/{uid}/);
assert.match(rules, /allow read: if isAdmin\(\) \|\| isOwnerOf\(uid\);/);
assert.match(fn, /exports\.syncPublicProfile = onDocumentWritten\(\{ document: "users\/{uid}", database: "homefinder" \}/);
assert.match(fn, /publicProfileFromUserData/);
assert.match(helper, /publicEmail/);
assert.match(helper, /verifiedBadge/);
assert.match(helper, /licensedBadge/);
assert.match(helper, /searchable/);
console.log('public-profile-projection: PASS');
